# html languages
language:
- zh-CN
- en

# aloha has different themes, default one is simple,
# you could change it with simple, xx
theme: simple

# main menu navigation
# icon name see http://semantic-ui.com/elements/icon.html
# menu:
#   Home:
#     name: homePage
#     value: /index.html
#     icon: home
#   archives:
#     name: archives
#     value: /archives/
#     icon: archive
#   Rss:
#     name: rss
#     value: /atom.xml
#     icon: rss
#   About:
#     name: aboutPage
#     value: /about
#     icon: mail


# some configuration about index page
index:
  showyear: false

# Miscelaneous
favicon: /favicon.jpg

# configure cdn source, in order to access faster
# default is //cdn.bootcss.com/
# if you deploy in China, I suggest you use //cdn.bootcss.com/
# start with // means it could auto to adapt to http or https
# maybe source url is different between multiple cdn services, ATTENTION please!
cdn: //cdn.bootcss.com

# stylesheets loaded in the <head>
stylesheets:
- local/css/aloha.css
#- local/css/semantic-ui/2.2.4/semantic.min.css
- cdn/semantic-ui/2.2.4/semantic.min.css
# - cdn/magnific-popup.js/1.1.0/magnific-popup.min.css

# scripts loaded in the end of the body
scripts:
- cdn/jquery/3.1.0/jquery.min.js
- cdn/semantic-ui/2.2.4/semantic.min.js
- local/js/aloha-events.js

